tech(api/causes): include GET/POST/PUT api
ramsunvtech/linkedin-clone-api pull request #39
Opened 2022-04-27 18:07 UTC by shangan23

Thanks for contributing on Linked In API!

To better assist you, please select the type of PR you want to create.

Click the "Preview" tab above, and click on the link for the PR type:

- [:bug: Bug fix](?template=bugfix.md)
- [:book: New Feature](?template=features.md)
- [:memo: Technical Update](?template=tech.md)

2022-04-27 18:49 UTC, jpukg requested changes

2022-04-27 18:49 UTC, jpukg commented on src/main/java/com/linkedin/network/service/impl/CausesServiceImpl.java
> +    public List<Causes> createCause(CausesRequest causesRequest) {
Why are we returning list of Causes as we create only one  in this method?. It can be changed to return only one Causes.

2022-04-27 18:49 UTC, jpukg commented on src/main/java/com/linkedin/network/service/impl/CausesServiceImpl.java
> +    CausesRepository causesRepository;
Always provide access modifier. If it is not going to be accessed outside of this class, then declare as private.

2022-04-27 18:49 UTC, jpukg commented on src/main/java/com/linkedin/network/api/causes.java
> +public class causes {
File name should start with Uppercase. Please change it to CausesController.

2022-04-27 18:49 UTC, jpukg commented on src/main/java/com/linkedin/network/api/causes.java
> +    CausesService causesService;
Access modifier?

2022-04-27 18:49 UTC, jpukg commented on src/main/java/com/linkedin/network/entity/Causes.java
> +@AllArgsConstructor
Why are we using @AllArgsConstructor and @NoArgsConstructor?. If not intentional, please remove these extra annotations,

2022-04-29 06:30 UTC, shangan23 commented on src/main/java/com/linkedin/network/api/causes.java
> +public class causes {
Changes done locally.

2022-04-29 06:32 UTC, shangan23 commented on src/main/java/com/linkedin/network/service/impl/CausesServiceImpl.java
> +    CausesRepository causesRepository;
Change done locally.

2022-04-29 06:35 UTC, shangan23 commented on src/main/java/com/linkedin/network/service/impl/CausesServiceImpl.java
> +    public List<Causes> createCause(CausesRequest causesRequest) {
Changes are done locally

2022-04-29 06:36 UTC, shangan23 commented on src/main/java/com/linkedin/network/api/causes.java
> +    CausesService causesService;
Change done locally

2022-04-29 07:58 UTC, merged