tech(mapstruct): Implement mapstruct for entity to DTO mapping
ramsunvtech/linkedin-clone-api pull request #45
Opened 2022-04-29 10:55 UTC by jpukg

## Issue ID
NA
## Summary
Map Entity to DTO using Mapstruct framework
## Steps to do this Tech Update

## Checklist

- [ ] Have you added the summary of what your changes do and why you'd like us to include them?
- [ ] Have you added the steps you followed?
- [x] Have the files been linted and formatted?
- [ ] Have the docs been updated to match the changes in the PR?
- [ ] Have the tests been updated to match the changes in the PR?
- [ ] Have you run the tests locally to confirm they pass?

### What is the need for this tech update, and the steps to reproduce the issue?

### What is the current status?
Completed
### How does this PR fix the problem, Screenshot Please?

2022-04-29 11:24 UTC, ramsunvtech requested changes

2022-04-29 11:24 UTC, ramsunvtech commented on pom.xml
> +        </dependency>
how about plugin where i've added the mapstruct

2022-04-29 11:24 UTC, ramsunvtech commented on src/main/java/com/linkedin/network/api/ProfileController.java
> +          ProfileDTO foundProfile = profileService.getProfileByUserId(userId);
this data is returned by JPA. should be Profile model instead of ProfileDTO. isn't it?

2022-04-29 11:24 UTC, ramsunvtech commented on src/main/java/com/linkedin/network/dto/ProfileDTO.java
> +package com.linkedin.network.dto;
are we fine with duplicating `ProfileRequest.java` to `ProfileDTO.java`

2022-04-29 11:24 UTC, ramsunvtech commented on src/main/java/com/linkedin/network/mapper/ProfileMapper.java
> +	// @Mapping(source = "birthday", target = "birthday", dateFormat = "yyyy-MM-dd")
can this commented code can be removed ?

2022-04-29 11:28 UTC, jpukg commented on pom.xml
> +        </dependency>
This is the actual dependency that is needed in the compile time. The plugin that you have added before for build and reporting.

2022-04-29 11:29 UTC, jpukg commented on src/main/java/com/linkedin/network/api/ProfileController.java
> +          ProfileDTO foundProfile = profileService.getProfileByUserId(userId);
Repository should return Entity and service will return DTO to the controller. This is how, it has been designed in this project.

2022-04-29 11:30 UTC, jpukg commented on src/main/java/com/linkedin/network/mapper/ProfileMapper.java
> +	// @Mapping(source = "birthday", target = "birthday", dateFormat = "yyyy-MM-dd")
Removed.

2022-04-29 11:30 UTC, jpukg commented on src/main/java/com/linkedin/network/dto/ProfileDTO.java
> +package com.linkedin.network.dto;
This is by design. ProfileRequest is for request and ProfileDTO for response.

2022-05-03 06:17 UTC, ramsunvtech commented on pom.xml
> +        </dependency>
got it.

2022-05-03 06:34 UTC, ramsunvtech commented on src/main/java/com/linkedin/network/api/ProfileController.java
> +          ProfileDTO foundProfile = profileService.getProfileByUserId(userId);
Need some clear diagram that helps to understand our current design like below.

![image](https://user-images.githubusercontent.com/1652629/166412972-51458b17-2ea6-4ef7-a752-97ffa2571c0d.png)

2022-05-03 06:42 UTC, ramsunvtech commented on src/main/java/com/linkedin/network/dto/ProfileDTO.java
> +package com.linkedin.network.dto;
can this be ProfileRequest and ProfileResponse

2022-05-03 06:58 UTC, jpukg commented on src/main/java/com/linkedin/network/dto/ProfileDTO.java
> +package com.linkedin.network.dto;
ProfileDTO should be okay.

2022-05-03 07:05 UTC, jpukg commented on src/main/java/com/linkedin/network/api/ProfileController.java
> +          ProfileDTO foundProfile = profileService.getProfileByUserId(userId);
Here I found an article which explains about the architecture and it has Mapstruct implementation.

2022-05-03 07:17 UTC, ramsunvtech approved these changes

2022-05-07 07:38 UTC, shangan23 approved these changes
lgtm

2022-05-07 07:38 UTC, merged